name: Integrate

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x,22.x]
        
    steps:
      - uses: actions/checkout@v4
      - name: use nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - name: "dependencies installed"
        run: npm i

      - name: "build command"
        run: npm run build
      
