name: Integrate

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x,22.x]
        
    steps:
      - uses: actions/checkout@v4
      - name: use nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: "dependencies of client installed"
        run: npm i
        working-directory: client

      - name: "build command of client"
        run: npm run build
        working-directory: client

      - name: "dependencies of server installed"
        run: npm i
        working-directory: server

      
